# Generated by Django 5.2.11 on 2026-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('max_workload_hours', models.IntegerField(default=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
