# Generated by Django 5.2.11 on 2026-02-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_merge_courses_enrollments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('block', models.CharField(max_length=32)),
                ('capacity', models.PositiveIntegerField()),
                ('equipment', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='block',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.classroom'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.subject'),
        ),
    ]
