# Generated by Django 5.2.11 on 2026-02-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0004_attendancesession_session_start_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreakSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-slot_date', 'start_time'],
                'unique_together': {('slot_date', 'start_time', 'end_time', 'label')},
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='food_ordering.breakslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='attendance.student')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='food_ordering.foodstall')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='food_ordering.foodstall')),
            ],
            options={
                'ordering': ['stall_id', 'sort_order', 'name'],
                'unique_together': {('stall', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='food_ordering.menucategory')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_ordering.foodstall')),
            ],
            options={
                'ordering': ['stall_id', 'name'],
                'unique_together': {('stall', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_ordering.foodorder')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_ordering.menuitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SlotCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_items', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('break_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='food_ordering.breakslot')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='food_ordering.foodstall')),
            ],
            options={
                'unique_together': {('stall', 'break_slot')},
            },
        ),
    ]
