# Generated by Django 5.2.11 on 2026-02-16 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancesession_session_start_at'),
        ('food_ordering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='ordered_by_label',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='ordered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodstall',
            name='max_items_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='break_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='food_ordering.breakslot'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to='attendance.student'),
        ),
    ]
