# Generated by Django 5.2.11 on 2026-02-20 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0003_foodorder_pickup_code_foodstall_operators_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='operated_food_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
