# Generated by Django 5.2.11 on 2026-02-21 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0004_menucategory_operators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slotcapacity',
            name='max_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PickupSlotHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_consumed', models.BooleanField(default=False)),
                ('break_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_slot_holds', to='food_ordering.breakslot')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_slot_holds', to='food_ordering.foodstall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_slot_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
