# Generated by Django 5.2.11 on 2026-02-21 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0006_foodstall_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='meal_deals', to='food_ordering.menuitem')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_deals', to='food_ordering.foodstall')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
