# Generated by Django 5.2.11 on 2026-02-09 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='session_start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
