# Generated by Django 5.2.11 on 2026-02-21 17:59

import django.db.models.deletion
from django.db import migrations, models


def _migrate_session_classrooms(apps, schema_editor):
    AttendanceSession = apps.get_model("attendance", "AttendanceSession")
    LegacyClassroom = apps.get_model("attendance", "Classroom")
    Block = apps.get_model("blocks", "Block")
    CanonicalClassroom = apps.get_model("classrooms", "Classroom")

    legacy_by_id = {
        c.id: c
        for c in LegacyClassroom.objects.all().only("id", "name", "block", "capacity")
    }

    block_by_name = {b.name: b for b in Block.objects.all().only("id", "name")}

    canonical_by_key = {}
    for c in CanonicalClassroom.objects.all().only("id", "block_id", "room_number"):
        canonical_by_key[(c.block_id, (c.room_number or "").strip())] = c

    qs = AttendanceSession.objects.exclude(classroom_id__isnull=True).only(
        "id",
        "classroom_id",
        "block",
        "capacity",
    )

    for s in qs.iterator(chunk_size=500):
        legacy = legacy_by_id.get(s.classroom_id)
        if legacy is None:
            s.classroom_id = None
            s.save(update_fields=["classroom"])
            continue

        blk_name = (getattr(legacy, "block", "") or "").strip()
        room_number = (getattr(legacy, "name", "") or "").strip()
        blk = block_by_name.get(blk_name)
        if blk is None or not room_number:
            s.classroom_id = None
            s.save(update_fields=["classroom"])
            continue

        canonical = canonical_by_key.get((blk.id, room_number))
        if canonical is None:
            s.classroom_id = None
            s.save(update_fields=["classroom"])
            continue

        s.classroom_id = canonical.id

        if not (getattr(s, "block", "") or "").strip():
            s.block = blk_name
        if getattr(s, "capacity", None) is None:
            s.capacity = getattr(canonical, "capacity", None)

        s.save(update_fields=["classroom", "block", "capacity"])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendancesession_course'),
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.classroom'),
        ),
        migrations.RunPython(_migrate_session_classrooms, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
