# Generated by Django 5.2.11 on 2026-02-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_unify_classrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='remedial_code',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='remedial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('makeup', 'Make-Up')], default='regular', max_length=16),
        ),
    ]
