# Generated by Django 5.2.11 on 2026-02-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancesession_remedial_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='attendance_mode',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('qr', 'QR'), ('face', 'Face')], max_length=16),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='mode',
            field=models.CharField(blank=True, choices=[('physical', 'Physical'), ('online', 'Online')], max_length=16),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='notify_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
