# Generated by Django 5.2.11 on 2026-02-16 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0002_foodorder_ordered_by_label_foodorder_ordered_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='foodstall',
            name='operators',
            field=models.ManyToManyField(blank=True, related_name='operated_food_stalls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
