# Generated by Django 5.2.11 on 2026-02-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ordering', '0005_slotcapacity_max_orders_pickupslothold'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodstall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_stalls/'),
        ),
    ]
