# Generated by Django 5.2.11 on 2026-02-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], max_length=10)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='blocks.block')),
            ],
            options={
                'unique_together': {('block', 'room_number')},
            },
        ),
    ]
